In [12]:
graph = {
    'A' : {'B' : 5, 'C' : 10, 'D' : 20},
    'B' : {'A' : 5, 'C' : 4},
    'C' : {'A' : 10, 'B' : 4, 'D' : 3},
    'D' : {'A' : 20, 'C' : 3}
}
finished = {}
unfinished = {node : float('inf') for node in graph.keys()}
previous_node = {}

start_point = 'A'
current_cost = 0
while True:
    for node,cost in graph[start_point].items() :
        if node in finished:
            continue
        new_cost = current_cost + cost
        if new_cost < unfinished[node]:
            unfinished[node] = new_cost
            previous_node[node] = start_point
    finished[start_point] = current_cost
    del unfinished[start_point]
    if len(unfinished) == 0:
        break
    lst = unfinished.items()
    lst.sort(key = lambda x: x[1])
    start_point, current_cost = lst[0][0], lst[0][1]

In [55]:
graph = {
    'A' : set(['B','C','D']),
    'B' : set(['A','E']),
    'C' : set(['A','F']),
    'D' : set(['A','G']),
    'E' : set(['B','H']),
    'F' : set(['C','I']),
    'G' : set(['D','J']),
    'H' : set(['E','I']),
    'I' : set(['F','H','J']),
    'J' : set(['G','I'])
}

In [61]:
graph['I'] - set(['A', 'C', 'B', 'D', 'F', 'E', 'G', 'I', 'H', 'J'])

set()

In [62]:
def bfs(graph,start):
    queue = [start]
    visited = []
    while queue:
        node = queue.pop(0)
        if node not in visited:
            visited.append(node)
            queue.extend(graph[node] - set(visited))
    return visited
bfs(graph,'A')

['A', 'C', 'B', 'D', 'F', 'E', 'G', 'I', 'H', 'J']

In [63]:
def dfs(graph,start):
    queue = [start]
    visited = []
    while queue:
        node = queue.pop()
        if node not in visited:
            visited.append(node)
            queue.extend(graph[node] - set(visited))
    return visited
dfs(graph,'A')

['A', 'D', 'G', 'J', 'I', 'F', 'C', 'H', 'E', 'B']

In [64]:
def bfs_path(graph,start,goal):
    route = [(start,[start])]
    while route:
        node,path = route.pop(0)
        for next in graph[node] - set(path):
            if next == goal:
                yield path + [next]
            else:
                route.append((next,path + [next]))
list(bfs_path(graph,'A','I'))

[['A', 'C', 'F', 'I'], ['A', 'B', 'E', 'H', 'I'], ['A', 'D', 'G', 'J', 'I']]

In [65]:
def dfs_path(graph,start,goal):
    route = [(start,[start])]
    while route:
        node,path = route.pop()
        for next in graph[node] - set(path):
            if next == goal:
                yield path + [next]
            else:
                route.append((next,path + [next]))
list(dfs_path(graph,'A','I'))

[['A', 'D', 'G', 'J', 'I'], ['A', 'B', 'E', 'H', 'I'], ['A', 'C', 'F', 'I']]

In [85]:
class Node():
    def __init__(self,val):
        self.val = val
        self.left = None
        self.right = None
        self.parent = None

class Tree():
    def __init__(self):
        self.root = None
        self.count = 0
        self.replacement = 0
    
    def get_root(self):
        return self.root
    
    def insert(self,val):
        if self.root == None:
            self.root = Node(val)
        else:
            self._insert(self.root,val)
            
    def _insert(self,node,val):
        if node.val > val:
            if node.left == None:
                node.left = Node(val)
                node.left.parent = node
            else:
                self._insert(node.left,val)
        else:
            if node.right == None:
                node.right = Node(val)
                node.right.parent = node
            else:
                self._insert(node.right,val)
                
    def find(self,val):
        if self.root != None:
            return self._find(self.root,val)
            
    def _find(self,node,val):
        if node.val == val:
            return node
        elif node.val > val and node.left != None:
            return self._find(node.left,val)
        elif node.val < val and node.right != None:
            return self._find(node.right,val)
        
    def print_tree(self):
        if self.root != None:
            self._print_tree(self.root)
        
    def _print_tree(self,node):
        if node != None:
            self._print_tree(node.left)
            print(node.val)
            self._print_tree(node.right)
            
    def delete_node(self,val):
        if self.root != None:
            self._delete_node(self.root,val)
            
    def _delete_node(self,node,val):
        if node.val == val:
            if node.left == None and node.right == None:
                if node.parent == None:
                    node.val = None
                else:
                    if node.val < node.parent.val:
                        node.parent.left = None
                    else:
                        node.parent.right = None
            else:
                self._delete_node_2(node)
                node.val = self.replacement
                
        elif node.val > val and node.left != None:
            self._delete_node(node.left ,val)
        elif node.val < val and node.right != None:
            self._delete_node(node.right ,val)
            
    def _delete_node_2(self,node):
        if node.right != None and self.count == 0:
            node = node.right
            self.count+=1
            self._delete_node_2(node)
        elif node.left != None and self.count == 0:
            node = node.left
            self.count+=2
            self._delete_node_2(node)
        elif node.left != None and self.count == 1:
            node = node.left
            self._delete_node_2(node)
        elif node.right != None and self.count == 2:
            node = node.right
            self._delete_node_2(node)
        else:
            self.count = 0
            self.replacement = node.val
            if node.val < node.parent.val:
                node.parent.left = None
            else:
                node.parent.right = None
            
            
            
            

In [94]:
tree = Tree()
tree.insert(20)
tree.insert(15)
tree.insert(25)
tree.insert(18)
tree.insert(12)
tree.insert(23)
tree.insert(30)
tree.insert(11)
tree.insert(14)
tree.insert(16)
tree.insert(19)
tree.insert(22)
tree.insert(24)
tree.insert(29)
tree.insert(35)
tree.print_tree()

11
12
14
15
16
18
19
20
22
23
24
25
29
30
35


In [101]:
import numpy as np
x = []
for i in xrange(20):
    x.append(np.random.randint(0,100))

In [103]:
def m_sort(lst):
    if len(lst) < 2:
        return lst
    result = []
    mid = len(lst)//2
    y = m_sort(lst[:mid])
    z = m_sort(lst[mid:])
    i = 0
    j = 0
    while i < len(y) and j < len(z):
        if y[i] < z[j]:
            result.append(y[i])
            i+=1
        else:
            result.append(z[j])
            j+=1
    result+=y[i:]
    result+=z[j:]
    return result

In [111]:
def q_sort(lst):
    if len(lst) < 2:
        return lst
    less = []
    equal = []
    greater = []
    pivot = lst[0]
    for element in lst:
        if element < pivot:
            less.append(element)
        elif element > pivot:
            greater.append(element)
        else:
            equal.append(element)
    return q_sort(less) + equal + q_sort(greater)

In [115]:
def binary_search(element,lst):
    lower_bound = 0
    upper_bound = len(lst)
    while lower_bound != upper_bound:
        mid = (lower_bound + upper_bound)//2
        if element == lst[mid]:
            return mid
        elif element > lst[mid]:
            lower_bound = mid +1
        else:
            upper_bound = mid
    return 'not found'

In [121]:
def binary_search(element,lst):
    lower_bound = 0
    upper_bound = len(lst)
    while lower_bound != upper_bound:
        mid = (lower_bound + upper_bound)//2
        if element > lst[mid]:
            lower_bound = mid +1
        else:
            upper_bound = mid
    return mid

In [123]:
def binary_search(element,lst):
    lower_bound = 0
    upper_bound = len(lst)
    while lower_bound != upper_bound:
        mid = (lower_bound + upper_bound)//2
        if element < lst[mid]:
            upper_bound = mid 
        else:
            lower_bound = mid +1
    return mid

In [128]:
def fib(n):
    a = 0
    b = 1
    for _ in xrange(n):
        a,b = b,a+b
    return a
        

In [129]:
for n in xrange(10):
    print(fib(n))

0
1
1
2
3
5
8
13
21
34


In [130]:
def GCD(x,y):
    if y > x:
        x,y = y,x
    if y == 0:
        return x
    return GCD(y, x % y)

In [134]:
GCD(19,13)

1

In [188]:
matrix =  np.array([[np.random.randint(0,3) for i in xrange(10)] for j in xrange(10)])

In [183]:
N = len(matrix)/2
start = N - 1
end = N
region = 1
while N > 0:
    sum_1 = np.sum(matrix[[start,end]][:,[start,end]]==0)
    sum_2 = np.sum(matrix[[start,end]][:,[start,end]]==2)
    if sum_1 > sum_2:
        print('winner is 1_st in Region {}'.format(region))
        break
    elif sum_2 > sum_1:
        print('winner is 2_nd in Region {}'.format(region))
        break    
    N-=1
    region+=1
    start-=1
    end+=1

winner is 1_st in Region 2


In [173]:
sum_1 = 5 
region = 2

In [178]:
 print('winner is {} in Region {}'.format(sum_1,region))

winner is 5 in Region 2


In [166]:
N = len(matrix)/2
start = N - 1
end = N

In [167]:
np.sum(matrix[[start,end]][:,[start,end]]==0)

2

In [153]:
matrix[[3,4],:]

array([[1, 0, 2, 1, 0, 2, 2, 0],
       [2, 0, 0, 0, 2, 0, 0, 2]])

In [194]:
matrix[[3,4]][:,[3,4]]

array([[1, 0],
       [0, 1]])

In [500]:
matrix =  np.array([[np.random.randint(0,3) for i in xrange(4)] for j in xrange(4)])
find_winner(matrix)

winner 2 in region 2


In [461]:
matrix

array([[2, 0, 1, 0],
       [1, 0, 2, 1],
       [1, 2, 0, 0],
       [0, 0, 2, 2]])

In [488]:
def find_winner(matrix,region = 0):
    if region < len(matrix)//2:
        n = len(matrix) -1
        counter = len(matrix)//2
        while counter > region:
            if counter == len(matrix) //2:
                new_matrix = matrix[1:n,:][:,1:n]
            else:
                new_matrix = new_matrix[1:n,:][:,1:n]
            counter-=1
            n-=2

        sum_1 = np.sum(new_matrix == 0)
        sum_2 = np.sum(new_matrix == 2)
        if sum_1 > sum_2:
            print('winner 1 in region {}'.format(region+1))
        elif sum_2 > sum_1:
            print('winner 2 in region {}'.format(region+1))
        else:
            find_winner(matrix,region+1)
            
    else:
        print('draw')

In [355]:
region = 0
n = len(matrix) -1
counter = n//2
while counter > region:
    if counter == (len(matrix) -1)//2:
        new_matrix = matrix[1:n,:][:,1:n]
    else:
        new_matrix = new_matrix[1:n,:][:,1:n]
    counter-=1
    n-=2
sum_1 = np.sum(new_matrix == 0)
sum_2 = np.sum(new_matrix == 2)
if sum_1 > sum_2:
    print('winner 1 in region {}'.format(region+1))
    
elif sum_2 > sum_1:
    print('winner 2 in region {}'.format(region+1))


In [356]:
new_matrix

array([[0, 2],
       [1, 1]])

In [274]:
matrix

array([[2, 2, 2, 1, 2, 1, 0, 0, 0, 1],
       [2, 1, 1, 1, 2, 0, 2, 2, 0, 1],
       [1, 2, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 2, 1, 2, 2, 2, 0, 2],
       [0, 1, 2, 2, 1, 2, 1, 1, 1, 1],
       [1, 2, 1, 1, 1, 1, 2, 2, 0, 2],
       [1, 0, 1, 2, 2, 1, 2, 0, 1, 0],
       [0, 2, 1, 2, 1, 0, 0, 0, 0, 0],
       [2, 1, 2, 2, 0, 0, 0, 1, 1, 0],
       [2, 2, 0, 1, 1, 2, 0, 0, 2, 0]])

In [272]:
new_matrix

array([[1, 1, 1, 2],
       [2, 0, 0, 0],
       [0, 0, 2, 1],
       [1, 2, 2, 1]])

In [260]:
vvv = matrix[1:9,:][:,1:9]

array([[1, 1, 1, 2, 0, 2, 2, 0],
       [2, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 2, 1, 2, 2, 2, 0],
       [1, 2, 2, 1, 2, 1, 1, 1],
       [2, 1, 1, 1, 1, 2, 2, 0],
       [0, 1, 2, 2, 1, 2, 0, 1],
       [2, 1, 2, 1, 0, 0, 0, 0],
       [1, 2, 2, 0, 0, 0, 1, 1]])

In [263]:
vv = vvv[1:7,:][:,1:7]

array([[0, 0, 0, 1, 0, 0],
       [0, 2, 1, 2, 2, 2],
       [2, 2, 1, 2, 1, 1],
       [1, 1, 1, 1, 2, 2],
       [1, 2, 2, 1, 2, 0],
       [1, 2, 1, 0, 0, 0]])

In [268]:
v = vv[1:5,:][:,1:5]

array([[2, 1, 2, 2],
       [2, 1, 2, 1],
       [1, 1, 1, 2],
       [2, 2, 1, 2]])

In [270]:
v[1:3,:][:,1:3]

array([[1, 2],
       [1, 1]])

In [254]:
matrix

array([[2, 2, 2, 1, 2, 1, 0, 0, 0, 1],
       [2, 1, 1, 1, 2, 0, 2, 2, 0, 1],
       [1, 2, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 2, 1, 2, 2, 2, 0, 2],
       [0, 1, 2, 2, 1, 2, 1, 1, 1, 1],
       [1, 2, 1, 1, 1, 1, 2, 2, 0, 2],
       [1, 0, 1, 2, 2, 1, 2, 0, 1, 0],
       [0, 2, 1, 2, 1, 0, 0, 0, 0, 0],
       [2, 1, 2, 2, 0, 0, 0, 1, 1, 0],
       [2, 2, 0, 1, 1, 2, 0, 0, 2, 0]])

In [266]:
new_matrix

array([[1, 1, 1, 2],
       [2, 0, 0, 0],
       [0, 0, 2, 1],
       [1, 2, 2, 1]])

In [234]:
new_matrix = matrix[1:9,:]
new_matrix = new_matrix[:,1:9]

In [236]:
new_matrix = new_matrix[1:7,:]
new_matrix = new_matrix[:,1:7]

In [238]:
new_matrix = new_matrix[1:5,:]
new_matrix = new_matrix[:,1:5]

In [241]:
new_matrix = new_matrix[1:3,:]
new_matrix = new_matrix[:,1:3]

In [242]:
new_matrix

array([[1, 2],
       [1, 1]])

In [239]:
new_matrix.shape

(4, 4)